const GUNS_CODE = {
	0: 'Hand-to-Hand',
	1: 'Knife',
	2: 'M92F (HG)',
	3: 'VZ61 (MAG)',
	4: 'Ithaca M37 (SG)',
	5: 'S75 (RIF)',
	6: 'Hand Grenade',
	7: 'Incendiary Grenade',
	8: 'Flash Grenade',
	9: 'SIG 556 (MAG)',
	10: 'Proximity Bomb',
	11: 'S&W M29 (MAG)',
	13: 'Rocket Launcher',
	14: 'Grenade Launcher [Empty/invalid]',
	15: 'Longbow',
	16: 'AK-74 (MAG)',
    17: 'SIG P226 (HG)',
	19: 'H&K MP5 (MAG)',
    21: 'Gatling Gun',
	22: 'M3 (SG)',
	23: 'Jail Breaker (SG)',
	25: 'Hydra (SG)',
	27: 'S&W M500 (MAG)',
	28: 'H&K PSG-1 (RIF)',
	30: 'M93R (HG)',
	32: 'Dragunov SVD (RIF)',
	34: 'Stun Rod',
	37: 'Grenade Launcher (Explosive)',
	38: 'Grenade Launcher (Acid)',
	39: 'Grenade Launcher (Nitrogen)',
	41: 'Samurai Edge (HG)',
    47: 'Gun Turrent',
	54: 'Egg (Rotten)',
	57: 'Grenade Launcher (Flame)',
	58: 'Grenade Launcher (Flash)',
	59: 'Grenade Launcher (Electric)',
	60: 'Egg (White)',
	61: 'Egg (Brown)',
	62: 'Egg (Gold)'
}

export const getWeaponsFromBuffer = (buffer: Buffer) => {
    return {
        'item': GUNS_CODE[buffer.readUInt8()],
        'enemiesKilled': buffer.readUInt32LE(0x4),
        'shotsFired': buffer.readUInt32LE(0x8),
        'shotsOnTarget': buffer.readUInt32LE(0xc),
        'headshots': buffer.readUInt32LE(0x10),
    }
}